"""add title for table tests

Revision ID: 4713bafa5bac
Revises: 2fca1cfc37f2
Create Date: 2026-10-09 20:15:29.709321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4713bafa5bac'
down_revision: Union[str, Sequence[str], None] = '2fca1cfc37f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('title', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests', 'title')
    # ### end Alembic commands ###
