"""delete unique text in answers

Revision ID: 60d21d67acc1
Revises: fb93f9ed8265
Create Date: 2026-08-05 17:33:44.104200

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "60d21d67acc1"
down_revision: str | Sequence[str] | None = "fb93f9ed8265"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("answers_text_key"), "answers", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("answers_text_key"),
        "answers",
        ["text"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
