"""add author_id to tests

Revision ID: e4db7c103ad5
Revises: 60d21d67acc1
Create Date: 2026-08-08 14:35:04.111872

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e4db7c103ad5"
down_revision: str | Sequence[str] | None = "60d21d67acc1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tests", sa.Column("author_id", sa.Uuid(), nullable=False))
    op.create_foreign_key(None, "tests", "users", ["author_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tests", type_="foreignkey")
    op.drop_column("tests", "author_id")
    # ### end Alembic commands ###
