"""add position for answers

Revision ID: 6dbd2b4081dd
Revises: e4db7c103ad5
Create Date: 2026-08-12 17:22:51.734514

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6dbd2b4081dd"
down_revision: str | Sequence[str] | None = "e4db7c103ad5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("answers", sa.Column("position", sa.Integer(), nullable=False))
    op.create_unique_constraint(
        "uq_answer_position", "answers", ["question_id", "position"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_answer_position", "answers", type_="unique")
    op.drop_column("answers", "position")
    # ### end Alembic commands ###
