"""add position for questions

Revision ID: 2fca1cfc37f2
Revises: 6dbd2b4081dd
Create Date: 2026-08-13 08:28:09.123779

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2fca1cfc37f2"
down_revision: str | Sequence[str] | None = "6dbd2b4081dd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("questions", sa.Column("position", sa.Integer(), nullable=False))
    op.create_unique_constraint(
        "uq_question_position", "questions", ["test_id", "position"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_question_position", "questions", type_="unique")
    op.drop_column("questions", "position")
    # ### end Alembic commands ###
