"""add foreign keys for test objects

Revision ID: fb93f9ed8265
Revises: f5b616ed539b
Create Date: 2026-07-24 13:08:22.144279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb93f9ed8265'
down_revision: Union[str, Sequence[str], None] = 'f5b616ed539b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('question_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'answers', 'questions', ['question_id'], ['id'])
    op.add_column('questions', sa.Column('test_id', sa.Uuid(), nullable=False))
    op.add_column('questions', sa.Column('text', sa.String(), nullable=False))
    op.create_foreign_key(None, 'questions', 'tests', ['test_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_column('questions', 'text')
    op.drop_column('questions', 'test_id')
    op.drop_constraint(None, 'answers', type_='foreignkey')
    op.drop_column('answers', 'question_id')
    # ### end Alembic commands ###
